### PR TITLE
Update: Descriptions and fixes

### PR DESCRIPTION
**Pull request by Clockiy**
- added descriptions for many parameters
- renamed some params for better understanding
- changed some params to be more similar to the default Adobe encoder
- moved 2-Pass param into VBR settings

### CODE REVIEW

**Comment by Clockiy** [comment]
- did a mistake at the level. i meant 6.2 for h265
- changed flac default compression rate because level 5 is a bit 'outdated' and the most cpus can handle 8 as easy as 5.
- will check hev_nvenc.json
- x264NalHrd is Signal HRD information which is required only for Blu-ray streams and television broadcast - because we are only encoding its useless

**Comment by Vouk** [comment]
- okay
- then please add "useDefaultValue": true, to this param
- can you show me a link where this is defined?
- okay
- There are users using this plugin for authoring blurays, keep it in

**Comment by Clockiy** [comment]
- 2Pass VBR only: http://help.encoding.com/knowledge-base/article/what-is-two-pass-encoding/ https://en.wikipedia.org/wiki/Variable_bitrate#Multi-pass_encoding_and_single-pass_encoding
- i added NAL again

**Comment by Vouk** [comment]
2pass for nvenc is different! there are no real 2 passes over the whole video. It just calculates one frame, so you need to check the nvidia nvenc specs. When i checked it there was no limitation to vbr, it is even included in some presets (i.e. slow)

**Comment by Clockiy** [comment]
I know about the spec dealing with medium, slow and so on presets that at slow it evaluates the file and uses 2-pass encoding. i know that there is no limitation to 2-pass cbr or other but it does not make any sense. because the 2-pass encoding can only be properly achieved with vbr, because of the variable bitrate.  2-Pass encoding is not required for CQP because it uses a Quantizer and calculates the images based on that value until each frame is processed. CRF is similar.
2-pass rate control modes help the encoder to gather statistics of the frame to be encoded before actually encoding it in the second pass, thereby resulting in optimal bit-utilization within the frame and consequently, higher encoding quality. This feature can not be used with CQP or CRF because these are based on rate fluctuations and fixed ratios.

**Comment by Vouk** [comment]
Adding descriptions

**Pull request merged**
